---
name: Go
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [oldstable, stable]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        if: matrix.os == 'ubuntu-latest' && matrix.go == 'stable'
        with:
          # Configure action using config file (option 1)
          config: ./.github/.testcoverage.yml

          # Configure action by specifying input parameters individually (option 2).
          # If you are using config file (option 1) you shouldn't use these parameters, however
          # specifying these action parameters will override appropriate config values.
          profile: cover.out
          local-prefix: github.com/manuelarte/gotimeplus
          threshold-file: 80
          threshold-package: 80
          threshold-total: 80
          ## when token is not specified (value '') this feature is turned off
          ## in this example badge is created and committed only for main branch
          git-token: ${{ secrets.GITHUB_TOKEN || '' }}
          ## name of branch where badges are stored
          ## ideally this should be orphan branch (see below how to create this branch)
          git-branch: badges
